InventoryItems = {
    -- "NAME" == "ItemName" "LABEL" == "F2 Name" "WEIGHT" == "KG MAX = 25 "" BAG = 45"
 
    { ["name"] = "phone", ["label"] = "iPhone 8", ["weight"] = 0.5, ["model"] = "prop_phone_ing", ["description"] = "Detta är din telefon." },
    { ["name"] = "repairkit", ["label"] = "Reparationskit", ["weight"] = 5 },
 
    { ["name"] = "fishingrod", ["label"] = "Fiskespö", ["weight"] = 2, ["model"] = "prop_fishing_rod_02" },
    { ["name"] = "fishinglure", ["label"] = "Fiskebete", ["weight"] = 0.05, ["stackable"] = true },
    { ["name"] = "fish", ["label"] = "Fisk", ["weight"] = 0.5, ["model"] = "prop_fish_slice_01", ["stackable"] = true },
 
    { ["name"] = "binoculars", ["label"] = "Kikare", ["weight"] = 1 },
    { ["name"] = "lighter", ["label"] = "Tändare", ["weight"] = 0.1, ["model"] = "p_cs_lighter_01" },
    { ["name"] = "cigarette1", ["label"] = "John Silver", ["weight"] = 0.01, ["model"] = "prop_cs_ciggy_01", ["stackable"] = true },
    { ["name"] = "cigarette2", ["label"] = "Camel Brezee", ["weight"] = 0.01, ["model"] = "prop_cs_ciggy_01", ["stackable"] = true },
    { ["name"] = "cigarette3", ["label"] = "Winston Blue", ["weight"] = 0.01, ["model"] = "prop_cs_ciggy_01", ["stackable"] = true },
    { ["name"] = "cigarette4", ["label"] = "Marlboro Röd", ["weight"] = 0.01, ["model"] = "prop_cs_ciggy_01", ["stackable"] = true },
    { ["name"] = "cigarette5", ["label"] = "L&M Röd", ["weight"] = 0.01, ["model"] = "prop_cs_ciggy_01", ["stackable"] = true },    
    { ["name"] = "joint", ["label"] = "Joint", ["weight"] = 0.01, ["model"] = "prop_sh_joint_01", ["stackable"] = true },
    { ["name"] = "meth", ["label"] = "Metamfetamin", ["weight"] = 0.01, ["model"] = "prop_meth_bag_01", ["stackable"] = true },
 
    { ["name"] = "marijuanaseed", ["label"] = "Marijuanafrö", ["weight"] = 0.01, ["stackable"] = true },
    { ["name"] = "marijuanapot", ["label"] = "Stor kruka", ["weight"] = 1.0 },
    { ["name"] = "marijuanaleaf", ["label"] = "Marijuanablad", ["weight"] = 0.01, ["stackable"] = true },

    {
        ["name"] = "coffee",
        ["label"] = "Kaffe",
        ["weight"] = 0.2,
        ["description"] = "Svart kaffe från en kaffeautomat."
    },

    { ["name"] = "cocaine", ["label"] = "1g Kokain", ["weight"] = 0.1, ["stackable"] = true, ["model"] = "prop_coke_block_half_a" },
    { ["name"] = "rizla", ["label"] = "Rizla", ["weight"] = 0.01, ["stackable"] = true },
    { ["name"] = "lockpick", ["label"] = "Dyrkset", ["weight"] = 5, ["model"] = "prop_cs_padlock" },
    { ["name"] = "rccar", ["label"] = "Radiostyrd bil", ["weight"] = 3, ["model"] = "prop_cs_package_01" },
    { ["name"] = "bandage", ["label"] = "Bandage", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_ld_health_pack", ["stackable"] = true },
    { ["name"] = "medkit", ["label"] = "Första Hjälpen", ["weight"] = 0.5, ["model"] = "prop_ld_health_pack", ["stackable"] = true },
    { ["name"] = "note", ["label"] = "Anteckning", ["weight"] = 0.3, ["model"] = "p_notepad_01_s" },
    { ["name"] = "umbrella", ["label"] = "Ihopfällbart Paraply", ["weight"] = 0.6, ["model"] = "p_amb_brolly_01" },
    { ["name"] = "guld", ["label"] = "Guld", ["weight"] = 1.0, ["model"] = "prop_gold_bar", ["stackable"] = true },
    { ["name"] = "pan", ["label"] = "Vaskpanna", ["weight"] = 0.7, ["stackable"] = true },
    { ["name"] = "fangalse", ["label"] = "Fängelse Kläder", ["weight"] = 1.0, ["stackable"] = true },
    { ["name"] = "gps", ["label"] = "GPS Sändare", ["weight"] = 1.0, ["stackable"] = true },
    { ["name"] = "ties", ["label"] = "Buntband Bankrån", ["weight"] = 0.6, ["model"] = "hei_prop_zip_tie_positioned", ["stackable"] = true },
    
    { ["name"] = "fakeplate", ["label"] = "Fake Plate", ["weight"] = 1 },
    
    { ["name"] = "lightningcable", ["label"] = "3 Meter Lightning USB Kabel", ["weight"] = 0.4, ["description"] = "Laddningskabel till en iPhone 8." },
    { ["name"] = "powerbank", ["label"] = "Deltaco Powerbank 20000mAh", ["weight"] = 1.4 },

    { ["name"] = "meat", ["label"] = "Rått kött", ["weight"] = 0.1 },
    { ["name"] = "leather", ["label"] = "Läder", ["weight"] = 0.2, ["stackable"] = true },

    --alcohol

    { ["name"] = "notebook", ["label"] = "Anteckningsblock (30 sidor)", ["model"] = "prop_notepad_01", ["weight"] = 0.4 },
    { ["name"] = "paper", ["label"] = "Utriven sida", ["model"] = "prop_notepad_01", ["weight"] = 0.1 },

    { ["name"] = "license", ["weight"] = 0.2, ["model"] = "prop_cs_credit_card" },
    { ["name"] = "huntinglicense", ["weight"] = 0.2, ["model"] = "prop_cs_credit_card" },

    { ["name"] = "champagne", ["label"] = "Louis Roederer Cristal Rose 2006 Champagne", ["weight"] = 2.0, ["model"] = "prop_champ_01a" },
    { ["name"] = "whisky", ["label"] = "Gold Medusa Whisky", ["weight"] = 1.2, ["model"] = "prop_cs_whiskey_bottle" },
    { ["name"] = "beer", ["label"] = "Bronzo Öl 33cl", ["weight"] = 0.7, ["model"] = "prop_beer_stz" },
    { ["name"] = "tequila", ["label"] = "Tequila 11cl", ["weight"] = 0.5, ["model"] = "prop_tequila" },
    { ["name"] = "wine", ["label"] = "Vin Glas 18cl", ["weight"] = 0.3, ["model"] = "p_wine_glass_s" },
    { ["name"] = "vodka", ["label"] = "Smirnoff Red Plain Vodka", ["weight"] = 0.9, ["model"] = "prop_vodka_bottle" },
 
    { ["name"] = "shovel", ["label"] = "Spade", ["weight"] = 5, ["model"] = "prop_ld_shovel" },

    { ["name"] = "sunglasses", ["label"] = "Solglasögon", ["weight"] = 1 },
    { ["name"] = "necklace", ["label"] = "Halsband", ["weight"] = 1 },
    { ["name"] = "chandelier", ["label"] = "Kristallkrona", ["weight"] = 2 },
    { ["name"] = "bowl", ["label"] = "Skål", ["weight"] = 1 },
    { ["name"] = "lpdisc", ["label"] = "LP Disk", ["weight"] = 2 },
    { ["name"] = "houseclock", ["label"] = "Väggklocka", ["weight"] = 2 },
 
    { ["name"] = "zipties", ["label"] = "Buntband", ["weight"] = 0.01, ["stackable"] = true, ["model"] = "hei_prop_zip_tie_positioned" },
 
    { ["name"] = "diamondring", ["label"] = "Diamantring", ["weight"] = 0.05 },
 
    { ["name"] = "alvedon", ["label"] = "Alvedon 500 mg", ["weight"] = 0.02, ["model"] = "prop_cs_pills" },
    { ["name"] = "ipren", ["label"] = "Ipren 4500 mg", ["weight"] = 0.01, ["model"] = "prop_cs_pills" },
    { ["name"] = "aqua", ["label"] = "Salvequick Aqua", ["weight"] = 0.1, ["model"] = "prop_cs_pills" },
    { ["name"] = "apoteket", ["label"] = "Apoteket Sterilt Snabbförband", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
    { ["name"] = "tramadol", ["label"] = "Tramadol 100 mg", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
    { ["name"] = "panodil", ["label"] = "Panodil 500 mg", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
    { ["name"] = "voltaren", ["label"] = "Voltaren 23,2 mg", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
    { ["name"] = "tiger", ["label"] = "Tiger Balsam 25 g", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
    { ["name"] = "idomin", ["label"] = "Idomin Salva 100 g", ["weight"] = 0.2, ["model"] = "prop_cs_pills" },
 
    { ["name"] = "modEngine", ["label"] = "Motordel", ["weight"] = 5 },
    { ["name"] = "modBrakes", ["label"] = "Bromsdel", ["weight"] = 5 },
    { ["name"] = "modTransmission", ["label"] = "Växellåda", ["weight"] = 5 },
    { ["name"] = "modSuspension", ["label"] = "Fjädring", ["weight"] = 5 },
    { ["name"] = "modTurbo", ["label"] = "Turbodel", ["weight"] = 5 },
    { ["name"] = "broken_modEngine", ["label"] = "Trasig Motordel", ["weight"] = 1 },
    { ["name"] = "broken_modBrakes", ["label"] = "Trasig Bromsdel", ["weight"] = 1 },
    { ["name"] = "broken_modTransmission", ["label"] = "Trasig Växellåda", ["weight"] = 1 },
    { ["name"] = "broken_modSuspension", ["label"] = "Trasig Fjädring", ["weight"] = 1 },
    { ["name"] = "broken_modTurbo", ["label"] = "Trasig Turbo", ["weight"] = 1 },
    { ["name"] = "part", ["label"] = "Bodypartdel", ["weight"] = 5 },
    { ["name"] = "broken_part", ["label"] = "Trasig Bodypartdel", ["weight"] = 1 },
    { ["name"] = "notepad", ["label"] = "Notepad", ["weight"] = 1 },
 
    { ["name"] = "water", ["label"] = "Vattenflaska (50cl)", ["weight"] = 0.5, ["stackable"] = true, ["model"] = "prop_ld_flow_bottle" },
    { ["name"] = "redbull", ["label"] = "Redbull (47cl)", ["weight"] = 0.5, ["stackable"] = true, ["model"] = "prop_ecola_can" },
    { ["name"] = "water2", ["label"] = "Loka Crush(50cl)", ["weight"] = 0.5, ["stackable"] = true, ["model"] = "prop_ld_flow_bottle" },
    { ["name"] = "bread", ["label"] = "Skinkmacka", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "bread2", ["label"] = "Varm macka", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "burger", ["label"] = "Hamburgare 150 gram", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_cs_burger_01" },
    { ["name"] = "pizza1", ["label"] = "Billys Pan Pizza", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "pizza2", ["label"] = "Gorbys Pirog", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "pizza3", ["label"] = "Rustica Pizza", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "pizza4", ["label"] = "Karins Lasagne", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_sandwich_01" },
    { ["name"] = "marabou1", ["label"] = "Marabou Mjölkchoklad", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_candy_pqs" }, 
    { ["name"] = "marabou2", ["label"] = "Marabou Daim", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_candy_pqs" },
    { ["name"] = "marabou3", ["label"] = "Marabou Jordgubbe", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "prop_candy_pqs" },
    { ["name"] = "snack1", ["label"] = "OLW Smash!", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "v_ret_ml_chips4" },
    { ["name"] = "snack2", ["label"] = "OLW Cheezdoodles", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "v_ret_ml_chips4" },
    { ["name"] = "snack3", ["label"] = "Estrella Grillchips", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "v_ret_ml_chips4" },
    { ["name"] = "snack4", ["label"] = "Estrella Sourcream & Onion Chips", ["weight"] = 0.2, ["stackable"] = true, ["model"] = "v_ret_ml_chips4" },          

    { ["name"] = "dildo", ["label"] = "Rosa Dildo", ["weight"] = 0.8, ["model"] = "prop_cs_dildo_01" },
    { ["name"] = "teddybear", ["label"] = "Teddybjörn", ["weight"] = 0.4, ["model"] = "prop_mr_raspberry_01" },
    { ["name"] = "supercharacter", ["label"] = "Superkraftsdocka Låda", ["weight"] = 1.2, ["model"] = "hei_prop_drug_statue_box_01" },
    { ["name"] = "keyboard", ["label"] = "Tangentbord", ["weight"] = 0.7, ["model"] = "hei_prop_hei_cs_keyboard" },
    { ["name"] = "scratchoff", ["label"] = "Trisslott", ["weight"] = 0.1, ["model"] = "p_cs_papers_03" },

    { ["name"] = "casing", ["weight"] = 0.01 },
    { ["name"] = "key", ["weight"] = 0.05, ["model"] = "prop_cs_keys_01" },
 
    --Bank heist
    { ["name"] = "thermite", ["label"] = "Thermite", ["weight"] = 1.0, ["model"] = "hei_prop_heist_thermite" },
    { ["name"] = "laptop", ["label"] = "Laptop", ["weight"] = 3.5, ["model"] = "hei_prop_hst_laptop" },

    --Weapons

    { ["name"] = "suppressor", ["label"] = "Ljuddämppare", ["weight"] = 0.5 },
    { ["name"] = "flashlight_weapon", ["label"] = "Vapenficklampa", ["weight"] = 0.5 },
    { ["name"] = "grip", ["label"] = "Grip", ["weight"] = 0.5 },
    { ["name"] = "sikte", ["label"] = "Sikte", ["weight"] = 0.5 },
 

 
    { ["name"] = "knife", ["label"] = "Kniv", ["weight"] = 0.5 },
    { ["name"] = "nightstick", ["label"] = "ASP Batong", ["weight"] = 1 },
    { ["name"] = "hammer", ["label"] = "Hammare", ["weight"] = 0.5 },
    { ["name"] = "bat", ["label"] = "Basebollträ", ["weight"] = 2, ["model"] = "p_cs_bbbat_01" },
    { ["name"] = "golfclub", ["label"] = "Golfklubba", ["weight"] = 0.7 },
    { ["name"] = "crowbar", ["label"] = "Kofot", ["weight"] = 3 },
    { ["name"] = "pistol", ["label"] = "Colt M1911", ["weight"] = 1 },
    { ["name"] = "combatpistol", ["label"] = "Sig Sauer P228", ["weight"] = 1.5 },
    { ["name"] = "appistol", ["label"] = "Colt SCAMP", ["weight"] = 1 },
    { ["name"] = "pistol50", ["label"] = "Desert Eagle", ["weight"] = 1.5 },
    { ["name"] = "microsmg", ["label"] = "Micro SMG", ["weight"] = 3 },
    { ["name"] = "smg", ["label"] = "MP5A3", ["weight"] = 3 },
    { ["name"] = "assaultsmg", ["label"] = "Magpul PDR", ["weight"] = 4 },
    { ["name"] = "assaultrifle", ["label"] = "AK 47", ["weight"] = 4 },
    { ["name"] = "carbinerifle", ["label"] = "M4A1", ["weight"] = 4 },
    { ["name"] = "advancedrifle", ["label"] = "CTAR-21", ["weight"] = 4 },
    { ["name"] = "mg", ["label"] = "PKP Pecheneg", ["weight"] = 4 },
    { ["name"] = "combatmg", ["label"] = "M249E1", ["weight"] = 4 },
    { ["name"] = "pumpshotgun", ["label"] = "Remington 870", ["weight"] = 4 },
    { ["name"] = "sawnoffshotgun", ["label"] = "Mossberg 500", ["weight"] = 4 },
    { ["name"] = "assaultshotgun", ["label"] = "UTAS UTS-15", ["weight"] = 4 },
    { ["name"] = "bullpupshotgun", ["label"] = "Kel-Tec KSG", ["weight"] = 4 },
    { ["name"] = "stungun", ["label"] = "X26 Taser", ["weight"] = 2 },
    { ["name"] = "sniperrifle", ["label"] = "PSG-1", ["weight"] = 20 },
    { ["name"] = "heavysniper", ["label"] = "M107", ["weight"] = 23 },
    { ["name"] = "remotesniper", ["label"] = "Remote Sniper", ["weight"] = 23 },
    { ["name"] = "grenadelauncher", ["label"] = "Milkor MGL", ["weight"] = 100000 },
    { ["name"] = "stinger", ["label"] = "stinger", ["weight"] = 1 },
    { ["name"] = "minigun", ["label"] = "minigun", ["weight"] = 1 },
    { ["name"] = "grenade", ["label"] = "grenade", ["weight"] = 1 },
    { ["name"] = "stickybomb", ["label"] = "stickybomb", ["weight"] = 1 },
    { ["name"] = "smokegrenade", ["label"] = "smokegrenade", ["weight"] = 0.5 },
    { ["name"] = "bzgas", ["label"] = "bzgas", ["weight"] = 0.5 },
    { ["name"] = "molotov", ["label"] = "Molotov Cocktail", ["weight"] = 1 },
    { ["name"] = "fireextinguisher", ["label"] = "Brandsläckare", ["weight"] = 4 },
    { ["name"] = "petrolcan", ["label"] = "Bränsledunk", ["weight"] = 5 },
    { ["name"] = "digiscanner", ["label"] = "digiscanner", ["weight"] = 2 },
    { ["name"] = "ball", ["label"] = "Tennis Boll", ["weight"] = 0.05 },
    { ["name"] = "snspistol", ["label"] = "H&K P7", ["weight"] = 2 },
    { ["name"] = "bottle", ["label"] = "Bottle", ["weight"] = 1 },
    { ["name"] = "gusenberg", ["label"] = "M1928A1 Thompson SMG", ["weight"] = 2 },
    { ["name"] = "specialcarbine", ["label"] = "H&K G36C", ["weight"] = 2 },
    { ["name"] = "heavypistol", ["label"] = "EWB 1911", ["weight"] = 2 },
    { ["name"] = "bullpuprifle", ["label"] = "Type 86-S", ["weight"] = 2 },
    { ["name"] = "dagger", ["label"] = "Jaktkniv", ["weight"] = 1 },
    { ["name"] = "vintagepistol", ["label"] = "FN Model 1910", ["weight"] = 2 },
    { ["name"] = "firework", ["label"] = "Firework", ["weight"] = 2 },
    { ["name"] = "musket", ["label"] = "Brown Bess", ["weight"] = 2 },
    { ["name"] = "heavyshotgun", ["label"] = "Saiga-12K", ["weight"] = 2 },
    { ["name"] = "marksmanrifle", ["label"] = "M39 EMR", ["weight"] = 2 },
    { ["name"] = "hominglauncher", ["label"] = "SA-7 Grail", ["weight"] = 2 },
    { ["name"] = "proxmine", ["label"] = "Proxmine Mine", ["weight"] = 2 },
    { ["name"] = "snowball", ["label"] = "Snöboll", ["weight"] = 2 },
    { ["name"] = "flaregun", ["label"] = "Signalpistol", ["weight"] = 2 },
    { ["name"] = "garbagebag", ["label"] = "Soppåse", ["weight"] = 5 },
    { ["name"] = "handcuffs", ["label"] = "Handfängsel", ["weight"] = 0.4 },
    { ["name"] = "combatpdw", ["label"] = "SIG Sauer MPX", ["weight"] = 2 },
    { ["name"] = "marksmanpistol", ["label"] = "Thompson-Center Contender G2", ["weight"] = 2 },
    { ["name"] = "knuckle", ["label"] = "Knogjärn", ["weight"] = 1 },
    { ["name"] = "hatchet", ["label"] = "Yxa", ["weight"] = 3 },
    { ["name"] = "railgun", ["label"] = "Railgun", ["weight"] = 1 },
    { ["name"] = "machete", ["label"] = "Machete", ["weight"] = 1 },
    { ["name"] = "machinepistol", ["label"] = "TEC-9", ["weight"] = 2 },
    { ["name"] = "switchblade", ["label"] = "Fällkniv", ["weight"] = 0.5 },
    { ["name"] = "revolver", ["label"] = "Taurus Raging Bull", ["weight"] = 2 },
    { ["name"] = "dbshotgun", ["label"] = "Zabala Short-Barreled Shotgun", ["weight"] = 2 },
    { ["name"] = "compactrifle", ["label"] = "Micro Draco AK Pistol", ["weight"] = 2 },
    { ["name"] = "autoshotgun", ["label"] = "AA-12", ["weight"] = 2 },
    { ["name"] = "battleaxe", ["label"] = "Krigsyxa", ["weight"] = 3 },
    { ["name"] = "compactlauncher", ["label"] = "M79 GL", ["weight"] = 2 },
    { ["name"] = "minismg", ["label"] = "Skorpion Vz. 61", ["weight"] = 3 },
    { ["name"] = "pipebomb", ["label"] = "pipebomb", ["weight"] = 2 },
    { ["name"] = "poolcue", ["label"] = "Biljardkö", ["weight"] = 1 },
    { ["name"] = "wrench", ["label"] = "Skiftnyckel", ["weight"] = 2 },
    { ["name"] = "flashlight", ["label"] = "Ficklampa", ["weight"] = 1 },
    { ["name"] = "nightvision", ["label"] = "nightvision", ["weight"] = 2 },
    { ["name"] = "parachute", ["label"] = "Fallskärm", ["weight"] = 4 },
    { ["name"] = "flare", ["label"] = "Flare", ["weight"] = 1 },
    { ["name"] = "pistol_mk2", ["label"] = "Beretta MK2", ["weight"] = 1 },
    { ["name"] = "carbinerifle_mk2", ["label"] = "Carbine MK2", ["weight"] = 4 },
    { ["name"] = "smg_mk2", ["label"] = "SMG MK2", ["weight"] = 4 },
    { ["name"] = "marksmanrifle_mk2", ["label"] = "SKS MK2", ["weight"] = 5 },
    { ["name"] = "pumpshotgun_mk2", ["label"] = "PUMPSHOTGUN MK2", ["weight"] = 5 },
    { ["name"] = "doubleaction", ["label"] = "doubleaction", ["weight"] = 2 },
    { ["name"] = "pistol_ammo_box", ["label"] = "Pistol Skottlåda", ["weight"] = 5, ["stackable"] = true, ["model"] = "prop_box_ammo01a"  },
    { ["name"] = "pistol_ammo", ["label"] = "Pistol Skott", ["weight"] = 0.05, ["stackable"] = true },
    { ["name"] = "smg_ammo_box", ["label"] = "SMG Skottlåda", ["weight"] = 5, ["stackable"] = true, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "smg_ammo", ["label"] = "SMG Skott", ["weight"] = 0.05, ["stackable"] = true },
    { ["name"] = "rifle_ammo_box", ["label"] = "Rifle Skottlåda", ["weight"] = 5, ["stackable"] = true, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "rifle_ammo", ["label"] = "Rifle Skott", ["weight"] = 0.05, ["stackable"] = true },
    { ["name"] = "shotgun_ammo_box", ["label"] = "Shotgun Skottlåda", ["weight"] = 5, ["stackable"] = true, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "shotgun_ammo", ["label"] = "Shotgun Skott", ["weight"] = 0.1, ["stackable"] = true, },
    { ["name"] = "sniper_ammo", ["label"] = "Sniper Skott", ["weight"] = 0.1, ["stackable"] = true, },
    { ["name"] = "sniper_ammo_box", ["label"] = "Sniper Skottlåda", ["weight"] = 0.1 * 16, ["stackable"] = false, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "mg_ammo", ["label"] = "MG Skott", ["weight"] = 0.1 * 16, ["stackable"] = false, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "flare_ammo", ["label"] = "Ljussignaler", ["weight"] = 0.1 * 16, ["stackable"] = false, ["model"] = "prop_box_ammo01a" },
    { ["name"] = "firework_ammo", ["label"] = "Fyverkerier", ["weight"] = 0.1 * 16, ["stackable"] = false, ["model"] = "prop_box_ammo01a" },
}
 